- name: Install Kubernete Minions Prerequisites
  hosts: kubernete-minions
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: check kubernetes server status
      stat: path=/opt/bin/flanneld
      register: status 
  roles:
  - host-config
  - kubernete-minion

- name: Install and Configure Kubernete Deployer
  hosts: kubernete-deployer
  remote_user: ubuntu
  sudo: yes
  roles:
  - { role: kubernete-deployer, when: "'{{ hostvars[groups['kubernete-minions'][0]]['status']['stat']['exists'] }}' == 'False'" }
